name: yatr
on:
  - push

jobs:
  yatr:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - distcheck
          - static-dist-linux-amd64

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run yatr
        env:
          CGO_ENABLED: "1"
          TARGET: "${{ matrix.target }}"
          DISTFILES_URL: "${{ secrets.DISTFILES_URL }}"
        run: |
          if [[ "x${{ matrix.target }}" = xstatic-dist-* ]]; then
              sudo apt-get install -y musl-tools
          fi
          curl -sSf https://yatr.rgm.io/run.sh | bash
